export const USER_STATE_CHANGE = "USER_STATE_CHANGE";

export const FETCH_CURRENT_USER_LESSONS = "FETCH_CURRENT_USER_LESSONS";

export const FETCH_ALL_LESSONS = "FETCH_ALL_LESSONS";

export const FETCH_ALL_FORMATIONS = "FETCH_ALL_FORMATIONS ";

export const FETCH_DATA = "FETCH_DATA ";

export const FETCH_CURRENT = "FETCH_CURRENT ";

export const FETCH_GC_USERS = "FETCH_GC_USERS ";
